/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WiderrufIndexRouteImport } from './routes/widerruf/index'
import { Route as UeberMichIndexRouteImport } from './routes/ueber-mich/index'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'
import { Route as DatenschutzIndexRouteImport } from './routes/datenschutz/index'
import { Route as AgbIndexRouteImport } from './routes/agb/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufIndexRoute = WiderrufIndexRouteImport.update({
  id: '/widerruf/',
  path: '/widerruf/',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichIndexRoute = UeberMichIndexRouteImport.update({
  id: '/ueber-mich/',
  path: '/ueber-mich/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzIndexRoute = DatenschutzIndexRouteImport.update({
  id: '/datenschutz/',
  path: '/datenschutz/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbIndexRoute = AgbIndexRouteImport.update({
  id: '/agb/',
  path: '/agb/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb/': typeof AgbIndexRoute
  '/datenschutz/': typeof DatenschutzIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/ueber-mich/': typeof UeberMichIndexRoute
  '/widerruf/': typeof WiderrufIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbIndexRoute
  '/datenschutz': typeof DatenschutzIndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/ueber-mich': typeof UeberMichIndexRoute
  '/widerruf': typeof WiderrufIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb/': typeof AgbIndexRoute
  '/datenschutz/': typeof DatenschutzIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/ueber-mich/': typeof UeberMichIndexRoute
  '/widerruf/': typeof WiderrufIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb/'
    | '/datenschutz/'
    | '/impressum/'
    | '/ueber-mich/'
    | '/widerruf/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agb' | '/datenschutz' | '/impressum' | '/ueber-mich' | '/widerruf'
  id:
    | '__root__'
    | '/'
    | '/agb/'
    | '/datenschutz/'
    | '/impressum/'
    | '/ueber-mich/'
    | '/widerruf/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbIndexRoute: typeof AgbIndexRoute
  DatenschutzIndexRoute: typeof DatenschutzIndexRoute
  ImpressumIndexRoute: typeof ImpressumIndexRoute
  UeberMichIndexRoute: typeof UeberMichIndexRoute
  WiderrufIndexRoute: typeof WiderrufIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf/': {
      id: '/widerruf/'
      path: '/widerruf'
      fullPath: '/widerruf/'
      preLoaderRoute: typeof WiderrufIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich/': {
      id: '/ueber-mich/'
      path: '/ueber-mich'
      fullPath: '/ueber-mich/'
      preLoaderRoute: typeof UeberMichIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum/'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz/': {
      id: '/datenschutz/'
      path: '/datenschutz'
      fullPath: '/datenschutz/'
      preLoaderRoute: typeof DatenschutzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb/': {
      id: '/agb/'
      path: '/agb'
      fullPath: '/agb/'
      preLoaderRoute: typeof AgbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbIndexRoute: AgbIndexRoute,
  DatenschutzIndexRoute: DatenschutzIndexRoute,
  ImpressumIndexRoute: ImpressumIndexRoute,
  UeberMichIndexRoute: UeberMichIndexRoute,
  WiderrufIndexRoute: WiderrufIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
