/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WissenIndexRouteImport } from './routes/wissen/index'
import { Route as WiderrufIndexRouteImport } from './routes/widerruf/index'
import { Route as UeberMichIndexRouteImport } from './routes/ueber-mich/index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen/index'
import { Route as KontaktIndexRouteImport } from './routes/kontakt/index'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'
import { Route as DatenschutzIndexRouteImport } from './routes/datenschutz/index'
import { Route as AgbIndexRouteImport } from './routes/agb/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WissenIndexRoute = WissenIndexRouteImport.update({
  id: '/wissen/',
  path: '/wissen/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufIndexRoute = WiderrufIndexRouteImport.update({
  id: '/widerruf/',
  path: '/widerruf/',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichIndexRoute = UeberMichIndexRouteImport.update({
  id: '/ueber-mich/',
  path: '/ueber-mich/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktIndexRoute = KontaktIndexRouteImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzIndexRoute = DatenschutzIndexRouteImport.update({
  id: '/datenschutz/',
  path: '/datenschutz/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbIndexRoute = AgbIndexRouteImport.update({
  id: '/agb/',
  path: '/agb/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb/': typeof AgbIndexRoute
  '/datenschutz/': typeof DatenschutzIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/ueber-mich/': typeof UeberMichIndexRoute
  '/widerruf/': typeof WiderrufIndexRoute
  '/wissen/': typeof WissenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbIndexRoute
  '/datenschutz': typeof DatenschutzIndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/ueber-mich': typeof UeberMichIndexRoute
  '/widerruf': typeof WiderrufIndexRoute
  '/wissen': typeof WissenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb/': typeof AgbIndexRoute
  '/datenschutz/': typeof DatenschutzIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/ueber-mich/': typeof UeberMichIndexRoute
  '/widerruf/': typeof WiderrufIndexRoute
  '/wissen/': typeof WissenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb/'
    | '/datenschutz/'
    | '/impressum/'
    | '/kontakt/'
    | '/leistungen/'
    | '/ueber-mich/'
    | '/widerruf/'
    | '/wissen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-mich'
    | '/widerruf'
    | '/wissen'
  id:
    | '__root__'
    | '/'
    | '/agb/'
    | '/datenschutz/'
    | '/impressum/'
    | '/kontakt/'
    | '/leistungen/'
    | '/ueber-mich/'
    | '/widerruf/'
    | '/wissen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbIndexRoute: typeof AgbIndexRoute
  DatenschutzIndexRoute: typeof DatenschutzIndexRoute
  ImpressumIndexRoute: typeof ImpressumIndexRoute
  KontaktIndexRoute: typeof KontaktIndexRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
  UeberMichIndexRoute: typeof UeberMichIndexRoute
  WiderrufIndexRoute: typeof WiderrufIndexRoute
  WissenIndexRoute: typeof WissenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wissen/': {
      id: '/wissen/'
      path: '/wissen'
      fullPath: '/wissen/'
      preLoaderRoute: typeof WissenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf/': {
      id: '/widerruf/'
      path: '/widerruf'
      fullPath: '/widerruf/'
      preLoaderRoute: typeof WiderrufIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich/': {
      id: '/ueber-mich/'
      path: '/ueber-mich'
      fullPath: '/ueber-mich/'
      preLoaderRoute: typeof UeberMichIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt/': {
      id: '/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt/'
      preLoaderRoute: typeof KontaktIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum/'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz/': {
      id: '/datenschutz/'
      path: '/datenschutz'
      fullPath: '/datenschutz/'
      preLoaderRoute: typeof DatenschutzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb/': {
      id: '/agb/'
      path: '/agb'
      fullPath: '/agb/'
      preLoaderRoute: typeof AgbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbIndexRoute: AgbIndexRoute,
  DatenschutzIndexRoute: DatenschutzIndexRoute,
  ImpressumIndexRoute: ImpressumIndexRoute,
  KontaktIndexRoute: KontaktIndexRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
  UeberMichIndexRoute: UeberMichIndexRoute,
  WiderrufIndexRoute: WiderrufIndexRoute,
  WissenIndexRoute: WissenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
